In [1]:
import pandas as pd
import numpy as np
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.linear_model import BayesianRidge
import random

In [2]:
data = np.random.random([1000,20])
null_data = np.empty([1000,2])
null_data[:] = np.nan
full_data = np.concatenate((data,null_data), axis=1)
full_data = np.random.permutation(full_data.flat)
full_data = full_data.reshape([1000,22])

In [6]:
print(data)

[[0.39732906 0.75773483 0.39483091 ... 0.0882337  0.4071472  0.97225093]
 [0.60867172 0.75913507 0.08950445 ... 0.01316137 0.92569153 0.47388331]
 [0.26805595 0.24149481 0.59741842 ... 0.71188824 0.31692344 0.68685495]
 ...
 [0.65058698 0.41520513 0.29112687 ... 0.7897728  0.8728034  0.38213251]
 [0.68878239 0.53705035 0.28307963 ... 0.59541191 0.05437906 0.21459225]
 [0.97503239 0.02580878 0.07815083 ... 0.68796701 0.65562676 0.00519959]]


In [7]:
imputer = IterativeImputer(BayesianRidge())
impute_data = pd.DataFrame(imputer.fit_transform(full_data))